### ISSUE TITLE
The label name in the first screen should be changed from “RISK LEVEL” to “PROJECT STATUS”.

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#1]
Change   the Label of the Risk Level Field in the "New Evaluation Dialog   Box" to "Project Status"
--

**Comment by gguptha** [comment]
Implemented via https://github.com/sajeevkhan/risk-rating-model/commit/304ead866978f9a177086328979d83cdc1b6af10
