### ISSUE TITLE
Evaluations: "Display PDF" button not enabled after the evaluation is done. See Screen Shot

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#24]
![capture](https://user-images.githubusercontent.com/1647692/52968503-ad380800-33ad-11e9-81a9-e17eae400c78.PNG)

**Comment by gguptha** [comment]
Implemented via https://github.com/sajeevkhan/risk-rating-model/commit/26bd06872e7143993ce468e993d3d92a4c49cea5
