### ISSUE TITLE
If LoanNumber is empty, Fetch Evaluations Fails;

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#26]
Hi Gopi,

I haved added a new attribute called loanEnquiryId to the riskmodel domain. In case, loan number is not assigned to an enquiry, then we need to fetch the riskmodels by loanEnquiryId. 
Also, on save of riskmodel, loanEnquiryId needs to be passed.

Sajeev

**Comment by sajeevkhan** [comment]
Hi Gopi,

I have added a new service to fetch evaluations by loanEnquiryId
/riskModel/loanEnquiryId/{loanEnquiryId} 

Regards
Sajeev

**Comment by gguptha** [comment]
Implemented via https://github.com/sajeevkhan/risk-rating-model/commit/a82c47039fadf19fa2bcd2388d015c219364047b
