### ISSUE TITLE
Display Scores only for Specific Purpose(Department)

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#3]
Score   against each parameter (ranging between 0 to 10) should not be visible to the   users of the Dept 1 and Dept 3.
--

**Comment by sajeevkhan** [comment]
There are three departments:
Purpose field is the same department
1. Risk
2. Appraisal
3. Monitoring
- Add new Attribute called RiskDepartment in the User Master 
If the user profile is Department Risk and Monitoring, then the score should not be visible in the evaluations detailed table

**Comment by gguptha** [comment]
Implemented via https://github.com/sajeevkhan/risk-rating-model/commit/c507162ca3c33478c0f269541a7dd54e6e9a6f36
