### ISSUE TITLE
Display User Name and Workflow Approver

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#4]
We also   need to show/ reflect the users in the WF for that project somewhere near   workflow status. It should reflect the user name and the overall rating made   by each users. It should reflect the users who have given the rating and also   should reflect the users would be doing the rating as subsequent users (if   updated in the system).

Fields   will be added for the following details:     - Created By User Name      - Reviewer User Name     The evaluation screen can only display the latest scores. However, the   specific scores which are modified by each user can be displayed in the   change document report.
--

--

**Comment by gguptha** [comment]
Implemented via https://github.com/sajeevkhan/risk-rating-model/commit/509b4ed382308cb9e975691203aaae062413fcfc
