### ISSUE TITLE
Assign Loan Enquiry to a User 

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#45]
Requirement 1: This function should only be applicable for department heads. 
Development Request: Add an attribute to the user master record called "Department Head". This should be a check box. 

Requirement 2: Assign Loan Inquiry to processor
Development request: 
1. Add the following attributes to the loan Application:
    - Project Department Initiator User : Type: UserName - String 
    - Monitoring Department Initiatior User: Type: UserName - String  
2. Process Flow: Search Projects, Select a Project from the search list -> Add a new Button "Assign Processors". Button should be enabled only if the user is a "Department Head" and only on select of an entry
3.  On Click of the Button "Assign Processors" , display a dialog box with the following attributes:
    -  Project Department Initiator : Drop down with users belonging to the "Project Department"
    -  Monitoring Department Initiator: Drop down with users belonging to the "Monitoring Department"
4. Save Button : Update the loan application with  the above attributes
                         Display a toast message that the loan project is updated
5. Cancel Button: Return to the search list

**Comment by gguptha** [comment]
Implemented via 

https://github.com/sajeevkhan/risk-rating-model/commit/a702a17604370a9cb1520f550138854112f4bbc8

https://github.com/gguptha/lms-enquiry/commit/6631b3e9ae900b922b320902b42dc043ad2596fd

Take and update of lms-enquiry as well ...
