### ISSUE TITLE
Search Loan Projects: Filter by User Name

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#46]
Based on User Profile:
1. If user is "admin" display all projects
2. If user belongs to "Risk Department" display all projects
3. If the user is department head, display all projects regardless of other criteria
4. If the user is not a Department Head, then 
_4.1 If user belongs to "Project Department " -> display all projects where the user is assigned as "Project Initiator User"
4. 2If user belongs to "Monitoring Department" -> display all projects where the user is assigned as "Monitoring Initiator User"_

**Comment by gguptha** [comment]
Implemented via https://github.com/sajeevkhan/risk-rating-model/commit/a506f42c4ad301b4b8bdaacb813f24c2616772eb.
