### ISSUE TITLE
Risk Rating in Parental Noctchup

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#5]
Source   of parent rating (ie CRISL/CARE etc) and rating associated to the   corresponding rating agency should populate automatically. Currently as shown   in the demo, it was being entered manually. Further working of parental notch   up should be as per the excel sheet and not as per PDF file. (as communicated   separately through e-mail dated 7th and 8th Feb)
--

**Comment by gguptha** [comment]
Implemented via https://github.com/sajeevkhan/risk-rating-model/commit/79a8e7073e47433b45597b36325cc96cd0877d1a
