### ISSUE TITLE
Rating Modifiers: None of the selection attributes are displayed for the users of dept. "Project Assessment"

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#50]

**Comment by sajeevkhan** [comment]
![image](https://user-images.githubusercontent.com/1647692/54162417-aef96680-4455-11e9-8448-111b6cdd6e59.png)

**Comment by gguptha** [comment]
Implemented via https://github.com/sajeevkhan/risk-rating-model/commit/70c31273c215ee0efd12f2369591b855778d7d74
