### ISSUE TITLE
Enable/Disable "Send for Approval Button" in the evaluation screen

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#56]
Enable "send for approval" only if the workflow status = "Created".  On Clicking, "Send for Approval"  and after receiving the response the status should be rechecked and the button should be enabled or disabled accordingly.
_**All other approvals will be processed from the Inbox only.**_

**Comment by gguptha** [comment]
Implemented via https://github.com/sajeevkhan/risk-rating-model/commit/02c83cfb42a2a0421739fbfd6053b677e42cebd5
