### ISSUE TITLE
Validation: If "monitoringDepartmentInitiator" and "projectDepartmentInitiator" is not assinged to a LoanEnquiry

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#60]
If If "monitoringDepartmentInitiator" and "projectDepartmentInitiator" is NOT assigned to a LoanEnquiry then, on click of the"Fetch Evaluations" button  we should throw an error message which is as follows and should not navigate to Fetch Evaluations.
**_"Project Officer and Monitoring Officer is not assigned to the Loan. Please request your department head to assign the officers"._**

**Comment by gguptha** [comment]
Implemented via https://github.com/sajeevkhan/risk-rating-model/commit/5d5112098a714ec53f12d352675740d490ccd908
