### ISSUE TITLE
Rating Modifiers Checkbox : On Unchecking the checkbox, all value statements should be reset as FALSE

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#65]
**Description of the issue as reported by PFS Testers**
_There   is another issue w.r.t Rating Modifiers. If we tick check box of APPLY RATING   MODIFIERS, system enables Rating Modifiers button. We make changes to rating   modifier paramteres as  YES or NO as   applicable and now if we again untick the check box of APPLY RATING   MODIFIERS, the rating paramerters do not change to NO positions.     Though it does not impact the evaluation rating, it is suggested to make   the all the modifiers back to NO position if the check box of APPLY RATING   MODIFIERS in unticked.
--_

**Comment by gguptha** [comment]
Implemented via https://github.com/sajeevkhan/risk-rating-model/commit/6cb128a94d19b0f2f62ab53e1ac9676030076bc2
