### ISSUE TITLE
Rating Modifiers: Label for Slider Buttons

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#69]
**_Issue as reported by PFS Testers:_**

In the   rating modifier tab, button enables to Yes/No STATE to the specific   statement.     For clarity in undersating the header should have Lable as " N / Y   "so as to identify the status. (Button on left side is N and if button   is on right side it is Y)
--

**Comment by gguptha** [comment]
Implemented via https://github.com/sajeevkhan/risk-rating-model/commit/4c90540d1c4e7981678b6f4912bec3f002def099
