### ISSUE TITLE
Evaluation: "Display PDF" button should be enabled as soon as evaluation is executed

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#7]

**Comment by gguptha** [comment]
I need the id to enable "Display as PDF" button. I will receive the id only when the evaluation is successfully executed. 

Please elaborate ...

**Comment by sajeevkhan** [comment]
Hi Gopi,

I meant after the evaluation is done .PDF button should be enabled..

Sent from a mobile device.
Please excuse brevity.

**Comment by gguptha** [comment]
Implemented via https://github.com/sajeevkhan/risk-rating-model/commit/26bd06872e7143993ce468e993d3d92a4c49cea5
