### ISSUE TITLE
Search Loan Enquiry Issue

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#70]
1. Search by Project   Name is working   . However, Wild Card Search is required for project      For e.g. *XXXX
2. Search by Loan Number is not working; Leading zeroes should be not be relevant in loan number search;    
3. it should be possible to search by Loan Number with wild card . For e.g. *XXXX   
--

**Comment by gguptha** [comment]
Implemented via ...
https://github.com/sajeevkhan/risk-rating-model/commit/1cd8db714f9e972b519954b2577e7ba853de8880
https://github.com/gguptha/lms-enquiry/commit/2ce32d982e141f1cae0d2d89c1a3090aed68c514
