### ISSUE TITLE
If Account Conduct was set as "Applicable", it should remain checked even when subsequent users process it

### ISSUE THREAD

**Issue by sajeevkhan** [sajeevkhan/risk-rating-model#74]
When   Swagat rates the project with account conduct as ticked   i.e.YES and when it goes to subsequent levels   (Sitesh /Neeraj/Devesh), it again shows account   conduct as unticked i.e. NO. However system shows   final score, as if account conduct is YES.          Once the same is enabled/disabled by initiator,  it should remain same (visible as such) for   subsequent approvals as well.
--

**Comment by gguptha** [comment]
To achieve this I need an attribute to store the value. For example, 

"Apply Rating Modifiers" is stored in the attribute "applyRatingModifiers"
"Apply Parental Notchup" is stored in the attribute "applyParentalNotchup"

**Comment by sajeevkhan** [comment]
Hi Gopi,

I think there is already an attribute for this in the RiskType entity.

Sajeev 

Sent from a mobile device.
Please excuse brevity.

**Comment by sajeevkhan** [comment]
Hi Gopi,

I have added a new attribute isAccountConductRiskApplicable on RiskType.
Please take an update.


Regards
Sajeev

Sent from Mail for Windows 10

**Comment by sajeevkhan** [comment]
Hi Gopi,

Wanted to give a status update to PFS... Let me know if we can we can resolve this issue in the next few days .....

Thanks 
Sajeev

Sent from a mobile device.
Please excuse brevity.
